// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types'; // Ensure this file is up-to-date with your new schema

// Use environment variables for URL and Key
const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_ANON_KEY;

// Get the current origin for redirect URLs (important for auth callbacks)
const origin = typeof window !== 'undefined'
  ? window.location.origin
  : 'http://localhost:3000'; // Or whatever your default server-side origin is

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client"; // Adjust path as per your project structure

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    autoRefreshToken: true,
    persistSession: true,
    detectSessionInUrl: true,
    flowType: 'pkce',
    storage: typeof window !== 'undefined' ? window.localStorage : undefined,
    storageKey: 'supabase.auth.token',
    onAuthStateChange: async (event, session) => {
      if (event === 'SIGNED_IN' || event === 'TOKEN_REFRESHED') {
        // Handle successful sign in
        console.log('Auth state changed:', event, session?.user?.email);
      }
      // You might want to add logic for SIGNED_OUT, USER_UPDATED etc.
    }
  },
  global: {
    headers: {
      'X-Client-Info': 'urban-gear-hub' // Good practice for identifying your client
    }
  }
});